# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fae45b5e77bf0b30a948623064e8af195f99e2bd35da3d656ff32b04706402e80781a768c4608f25de24a45bb33c7eeaa3dd1de192646a91d51ae4675307bd2e

test:
  secret_key_base: 91262975039a29acf2521af7f6b5444ce0eb4c81cc74cdd5b2aca64b4529ed2780da473d72ee6c4ecf8bc72cdfedaa79722cd90d06e7d14c423a51b2a99e9fd0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
